version: "3.9"

services:
  postgresql:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER= armboy122
      - POSTGRES_PASSWORD= armboy122
      - POSTGRES_DB= armboy122
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
